# Generated by Django 4.2.17 on 2026-09-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='first_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_comment', to='articles.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='articles.comment'),
        ),
    ]
